Adding removing schema example from docs.
reactioncommerce/reaction-example-plugin pull request #2
Opened 2016-09-25 20:32 UTC by mikeumus

Adding the "Removing Fields from a Schema" section of the "Creating a Plugin" article. 
Got this working together with @jshimko in a shared Cloud9 IDE Workspace.

2017-04-18 03:13 UTC, brent-hoover requested changes
Thanks for this. Just a couple of little changes.

2017-04-18 03:13 UTC, zenweasel commented on lib/collections/accounts.js
> +export const Profile = new SimpleSchema({
If we are just modifying the `Account` schema, we should import these from `lib/schemas` rather than copying them over.

2017-04-18 03:13 UTC, zenweasel commented on lib/schemas.js
> +Accounts.attachSchema(AccountsSchema, {replace: true});
Need spaces around brackets here

2017-04-18 03:13 UTC, zenweasel commented on lib/collections/accounts.js
> +import { SimpleSchema } from "meteor/aldeed:simple-schema";
To make this consistent with the main project, should be make this `lib/collections/schemas`?

2017-04-18 03:13 UTC, zenweasel commented on lib/collections/accounts.js
> +  name: {
Let's put a comment in somewhere to indicate what field we have eliminated? (I assume that's what you did here?)

2017-07-30 23:32 UTC, carlos-olivera approved these changes

2017-08-02 01:59 UTC, mikeumus commented on lib/collections/accounts.js
> +import { SimpleSchema } from "meteor/aldeed:simple-schema";
Is there a `SimpleSchema` in `reaction/lib/collections/schemas` or what am I importing?

2017-08-02 02:32 UTC, zenweasel commented on lib/collections/accounts.js
> +import { SimpleSchema } from "meteor/aldeed:simple-schema";
I meant to just move the file location to be consistent with the rest. (there's no good place for file-level comments on GH)

2017-08-03 01:14 UTC, mikeumus commented on lib/collections/accounts.js
> +export const Profile = new SimpleSchema({
Like add the `const Profile` to [`/lib/schemas.js`](https://github.com/mikeumus/reaction-example-plugin/blob/3ba6d468388d7d3a6262f6072572c7973b411b92/lib/schemas.js) and import it from there?

2017-08-03 01:18 UTC, zenweasel commented on lib/collections/accounts.js
> +export const Profile = new SimpleSchema({
Sorry, I think I may have misread this because the comment says `Accounts Schema`. You can disregard that comment.

2017-08-03 03:26 UTC, mikeumus commented on lib/collections/accounts.js
> +import { SimpleSchema } from "meteor/aldeed:simple-schema";
So move the `schemas.js` from `lib/schemas.js` to `lib/collections/schemas.js` ?

2017-08-03 03:27 UTC, zenweasel commented on lib/collections/accounts.js
> +import { SimpleSchema } from "meteor/aldeed:simple-schema";
That's my suggestion, yes.

2017-08-03 03:56 UTC, mikeumus commented on lib/collections/accounts.js
> +  name: {
ehh.. I don't remember what...

Maybe I can just comment this link:
``` javascript
// Removing Fileds from a Schema
// https://github.com/reactioncommerce/reaction-docs/blob/f07e131f42e1e12db283e89820580d98e8a338b7/developer/tutorial/creating-a-plugin.md#removing-fields-from-a-schema
```

2017-08-03 04:01 UTC, mikeumus commented on lib/collections/accounts.js
> +import { SimpleSchema } from "meteor/aldeed:simple-schema";
k, see 7d7a66f

2017-11-09 02:16 UTC, brent-hoover approved these changes

2017-11-09 02:16 UTC, merged

2017-11-09 18:40 UTC, machikoyasuda commented
Woot! @mikeumus - longest running PR I've seen on Reaction in a while :)